// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLjwGQswud0mrvE9nXSn2x2oji92zHeaI',
    appId: '1:965375227828:web:1f40a1db2208a6284be4e1',
    messagingSenderId: '965375227828',
    projectId: 'transportapp-b656f',
    authDomain: 'transportapp-b656f.firebaseapp.com',
    storageBucket: 'transportapp-b656f.firebasestorage.app',
    measurementId: 'G-QVW3C4HEWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDejT-52Sr8l6Pnw9DpxRfP22sADSrL23w',
    appId: '1:965375227828:android:129d871adc8afea24be4e1',
    messagingSenderId: '965375227828',
    projectId: 'transportapp-b656f',
    storageBucket: 'transportapp-b656f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmWaEOxQfy1ZifKQ5BQZdT4Lq80wOTuAU',
    appId: '1:965375227828:ios:5ef66327645481f74be4e1',
    messagingSenderId: '965375227828',
    projectId: 'transportapp-b656f',
    storageBucket: 'transportapp-b656f.firebasestorage.app',
    iosBundleId: 'com.example.transportAppMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmWaEOxQfy1ZifKQ5BQZdT4Lq80wOTuAU',
    appId: '1:965375227828:ios:5ef66327645481f74be4e1',
    messagingSenderId: '965375227828',
    projectId: 'transportapp-b656f',
    storageBucket: 'transportapp-b656f.firebasestorage.app',
    iosBundleId: 'com.example.transportAppMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLjwGQswud0mrvE9nXSn2x2oji92zHeaI',
    appId: '1:965375227828:web:7a4ae1da1f45f5e54be4e1',
    messagingSenderId: '965375227828',
    projectId: 'transportapp-b656f',
    authDomain: 'transportapp-b656f.firebaseapp.com',
    storageBucket: 'transportapp-b656f.firebasestorage.app',
    measurementId: 'G-JYE2XJFQY7',
  );
}
